# Configuración predeterminada para Ollama/Mistral
# Este archivo contiene los parámetros que controlan la generación de texto con Ollama

ollama:
  modelo: "mistral"
  host: "http://ollama:11434"

# Parámetros para generación de SQL
sql:
  num_predict: 50       # SQL es típicamente más corto
  temperature: 0.2      # Baja temperatura para SQL más determinístico
  top_k: 40
  top_p: 0.9
  num_gpu: 1
  num_thread: 4

# Parámetros para generación de chat
chat:
  num_predict: 100      # Limitar la longitud de respuesta
  temperature: 0.7      # Temperatura moderada para respuestas conversacionales
  top_k: 40
  top_p: 0.9
  num_gpu: 1
  num_thread: 4