ai_provider: claude
chat:
  configType: chat
  model: claude-2.1
  num_gpu: 1
  num_predict: 220
  num_thread: 8
  provider: claude
  temperature: 0.5
  top_k: 48
  top_p: 0.9
claude:
  model: claude-2.1
ollama:
  host: http://ollama:11434
  modelo: mistral
openai:
  model: gpt-4o
sql:
  configType: sql
  model: claude-2.1
  num_gpu: 1
  num_predict: 500
  num_thread: 4
  provider: claude
  temperature: 1
  top_k: 40
  top_p: 1
